# LoRA生成用の設定ファイル例

# 複数のLoRAファイルを指定
lora_generation:
  lora_files:
    - "runs/demo_sana_idefics2/man-smile/0/lora_o-000099.pt"
    - "runs/bald_sana_idefics2/man-bald/0/lora_o-000099.pt"  # 複数指定可能
  lora_weights:
    - 1.0  # 最初のLoRAの重み
    - 1.0 # 2番目のLoRAの重み（複数LoRA使用時）
  
  # 比較用オプション
  generate_original: true  # LoRAなしのオリジナル画像も生成するか
  original_folder: "original"  # オリジナル画像の保存フォルダ名
  lora_folder: "with_lora"    # LoRA適用画像の保存フォルダ名

# 生成設定
generation:
  prompts:
    - "Photo of a man"
  num_images_per_prompt: 4
  seed: 42

# 出力フォルダ（CLI overrideで上書き可能）
save_folder: "generated_with_lora"
